version: "3.4"

services:
  postgres:
    image: postgres:11.7-alpine
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  sqs:
    image: s12v/elasticmq
    ports:
      - "9324:9324"
    volumes:
      - ./src/queue/local-sqs-setup.conf:/etc/elasticmq/elasticmq.conf
  psp:
    build:
      context: .
    entrypoint: ["sh", "scripts/start.sh"]
    volumes:
      - .:/psp
      - /psp/node_modules
    environment:
      - NODE_ENV=test
      - APP_TYPE=server
      - SQS_ENDPOINT=http://sqs:9324
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_NAME=postgres
    ports:
      - "3000:3000"
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3000/health"]
      interval: 10s
      retries: 5
    depends_on:
      - postgres
      - sqs
  payable-worker:
    build:
      context: .
    entrypoint: ["sh", "scripts/start.sh"]
    volumes:
      - .:/psp
      - /psp/node_modules
    environment:
      - NODE_ENV=test
      - SQS_ENDPOINT=http://sqs:9324
      - APP_TYPE=worker
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_NAME=postgres
    depends_on:
      - postgres
      - sqs
  migrate:
    build: 
      context: .
    entrypoint: node_modules/.bin/sequelize db:migrate --config src/database/config.js --migrations-path src/database/migrations/
    environment:
      - NODE_ENV=test
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_NAME=postgres
    volumes:
      - .:/psp
      - /psp/node_modules
    depends_on:
      - postgres
  test:
    build:
      context: .
    entrypoint: npm run test
    environment:
      - NODE_ENV=test
      - SQS_ENDPOINT=http://sqs:9324
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_NAME=postgres
    volumes:
      - .:/psp
      - /psp/node_modules
    depends_on:
      - migrate
