version: '3.4'

services:
  postgres:
    network_mode: host
    image: postgres
    volumes:
      - $HOME/docker/volumes/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
        - POSTGRES_DB=postgres
        - POSTGRES_PASSWORD=postgres
        - PGDATA=/tmp
  sqs:
    image: s12v/elasticmq
    ports:
      - "9324:9324"
    volumes:
      - ./infrastructure/sqs.conf:/etc/elasticmq/elasticmq.conf
  psp:
    network_mode: host
    build: .
    entrypoint: node src/bin/server.js
    volumes:
      - .:/psp
      - /psp/node_modules
    environment:
      - NODE_ENV=test
      - SQS_ENDPOINT=http://localhost:9324
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - sqs
  migrate:
    network_mode: host
    build: .
    entrypoint: ["sh", "docker-test-entrypoint.sh"]
    environment:
      - NODE_ENV=test
    volumes:
      - .:/psp
      - /psp/node_modules
    depends_on:
      - postgres
  test:
    network_mode: host
    build: .
    entrypoint: npm run test
    environment:
      - NODE_ENV=test
    volumes:
      - .:/psp
      - /psp/node_modules
    depends_on:
      - migrate
