FROM node:12.10-alpine

WORKDIR /psp

COPY package.json /psp/package.json
COPY scripts/start-server.sh /psp
COPY scripts/start-payable-worker.sh /psp


RUN npm i

COPY . .

EXPOSE 3000
ENTRYPOINT ["sh", "-c", "/app/start.sh"]