version: "3.4"

services:
  postgres:
    network_mode: host
    image: postgres
    volumes:
      - $HOME/docker/volumes/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/tmp
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  sqs:
    image: s12v/elasticmq
    ports:
      - "9324:9324"
    volumes:
      - ./infrastructure/sqs.conf:/etc/elasticmq/elasticmq.conf
  psp:
    network_mode: host
    build: .
    entrypoint: node src/bin/server.js
    volumes:
      - .:/psp
      - /psp/node_modules
    environment:
      - NODE_ENV=test
      - SQS_ENDPOINT=http://localhost:9324
    ports:
      - "3000:3000"
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3000/health"]
      interval: 10s
      retries: 5
    depends_on:
      - postgres
      - sqs
  migrate:
    network_mode: host
    build: .
    entrypoint: node_modules/.bin/sequelize db:migrate --config src/database/config.js --migrations-path src/database/migrations/
    environment:
      - NODE_ENV=test
    volumes:
      - .:/psp
      - /psp/node_modules
    depends_on:
      - postgres
  test:
    network_mode: host
    build: .
    entrypoint: npm run test
    environment:
      - NODE_ENV=test
    volumes:
      - .:/psp
      - /psp/node_modules
    depends_on:
      - migrate
