FROM node:12.10-alpine as builder

WORKDIR /psp

COPY package.json .

RUN npm install --production

FROM node:12.10-alpine as production

WORKDIR /psp

COPY /src /psp/src
COPY package.json .
COPY .sequelizerc .


COPY --from=builder /psp/node_modules /psp/node_modules

EXPOSE 3000

ENTRYPOINT [ "npm", "start" ]