user  nginx;
events {
    worker_connections   1000;
}

http {
    upstream app {
        server psp:3001;
    }
    server {
        listen 3000;
        location / {
            proxy_pass http://app;
        }
    }
}
